{
 "title": "TrustyAI Visualization Sources",
 "time": { "from": "2023-08-10T09:29:56.467Z", "to": "2023-08-10T09:39:46.165Z" },
 "templating": {
  "list": [
   { "name": "model", "label": "Model", "query": { "query": "label_values(model)" } },
   { "name": "metric", "label": "Metric", "query": { "query": "label_values(metricName)" } },
   {
    "name": "request",
    "query": {
     "query": "query_result({model=\"$model\", metricName=~\"$metric\", metricName!~\"trustyai_model_\"})"
    }
   },
   {
    "name": "requestName",
    "query": {
     "query": "query_result({model=\"$model\", metricName=~\"$metric\", metricName!~\"trustyai_model_\",  request=\"$request\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TrustyAI Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Registed Models",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "trustyai_model_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Model Observations: $model",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "trustyai_model_observations{model=\"$model\"}",
       "legendFormat": "Model Observations"
      }
     ]
    }
   ]
  },
  { "title": "Current Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$requestName",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
   "repeat": "request",
   "targets": [
    {
     "expr": "{request=\"$request\"}"
    }
   ]
  }
 ]
}