{
 "title": "TrustyAI Default Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "model", "label": "Model", "query": { "query": "label_values(model)" } },
   { "name": "metric", "label": "Metric", "query": { "query": "metrics(trustyai_(?!model_))" } },
   {
    "name": "request",
    "query": {
     "query": "query_result({model=\"$model\", __name__=~\"$metric\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "TrustyAI Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Registed Models",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trustyai_model_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Observations: $model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "trustyai_model_observations{model=\"$model\"}",
     "legendFormat": "Model Observations"
    }
   ]
  },
  { "title": "All Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TrustyAI Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "repeat": "request",
   "targets": [
    {
     "expr": "{request=\"$request\"}",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}